sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t rsb2593/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true rsb2593/docker-react npm run test -- --coverage
